version: "3.9"
services:
  barber-mysql:
    image: mysql:8.0
    container_name: barber-mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: sijan123
      MYSQL_DATABASE: fadebook
    ports:
      - "3306:3306"
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 5s
      retries: 5
      start_period: 10s

  barber-app:
    build: .
    container_name: barber-app
    restart: always
    depends_on:
      barber-mysql:
        condition: service_healthy
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://barber-mysql:3306/fadebook?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: sijan123
      SPRING_JPA_HIBERNATE_DDL_AUTO: update
      SPRING_JPA_PROPERTIES_HIBERNATE_DIALECT: org.hibernate.dialect.MySQL8Dialect
    ports:
      - "8080:8080"
